//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week8LoginDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artile
    {
        public int NewsId { get; set; }
        public string AuthorId { get; set; }
        public string ArticleText { get; set; }
    }
}
